hosts:
  - localhost:8091
username: user
password: 123456
bucketName: dcp-test
logging:
  level: info
dcp:
  group:
    name: groupName
    membership:
      type: static
sql:
  host: localhost
  user: user
  password: password
  dbName: example
  port: 5432
  driverName: postgres