hosts:
  - localhost:8091
username: user
password: password
bucketName: dcp-test
dcp:
  group:
    name: groupName
    membership:
      type: static
metadata:
  type: couchbase
  config:
    bucket: checkpoint-bucket-name
    scope: _default
    collection: _default
sql:
# TODO