version: "3.8"
services:
  couchbase:
    build:
      context: "test/couchbase"
    ports:
      - "8091:8091"
      - "11210:11210"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://user:123456@localhost:8091/pools/default/buckets/dcp-test" ]
      interval: 2s
      timeout: 3s
      retries: 60
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=example
    ports:
      - 5432:5432
    networks:
      - postgres-db-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@test.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - 16543:80

    networks:
      - postgres-db-network

networks:
  postgres-db-network:
    driver: bridge